name = "aio"
account_id = "${ACCOUNT_ID}"
compatibility_date = "2024-06-01"
main = "worker.js"
workers_dev = true

[vars]
SUPABASE_URL = "https://cbskpfllobxxqryrxvkt.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
