name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "df.game.naver.com.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "ads.ruangguru.com.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "api.midtrans.com.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "bakrie.ac.id.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "unnes.ac.id.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "investor.fb.com.aio.proxybox.dpdns.org", custom_domain = true },
  { pattern = "blog.webex.com.aio.proxybox.dpdns.org", custom_domain = true },  
]

[[kv_namespaces]]
binding = "SIREN"
id = "c31f6ec0bc71473b985003909feae12d"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://underconstruction.proxybox.dpdns.org/"
PROXY_KV_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/kvProxyList.json"
