name = "${WORKER_NAME}"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

routes = [
  { pattern = "${WORKER_DOMAIN}", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "5bbfc353fd1247ee861d1b178742eaff"

[build]
command = "cargo install worker-build && worker-build --release"

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://unlimited.biz.id/"
PROXY_KV_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/kvProxyList.json"
