name: Deploy CF Workers

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy multiple Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          WORKERS=("siren" "siren2" "siren3" "siren4" "siren5")
          cp wrangler.toml wrangler.toml.bak
          
          for NAME in "${WORKERS[@]}"; do
            echo "Deploying $NAME..."
            sed -i.bak "s/^name = \".*\"/name = \"$NAME\"/" wrangler.toml
            wrangler deploy
          done
          
          mv wrangler.toml.bak wrangler.toml
