name: Deploy Workers Cloudflare Accounts

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - name: unlimited.biz.id
            account_id: 58d2b0fb56ebb7f76362b15c0f50fe93
            token_secret: CF_TOKEN_UNLIMITED_BIZ_ID
            kv_namespace_id: b10d811755564eebb49d0bb7ac2c4f82

          - name: nolimit.dpdns.org
            account_id: afb4250e641b8d082662780e98b64b95
            token_secret: CF_TOKEN_NOLIMIT_DPDNS_ORG
            kv_namespace_id: f26cdd83d19047daa6877faabe982183

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js & Wrangler
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g wrangler

      - name: Deploy 30 Workers for ${{ matrix.config.name }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets[matrix.config.token_secret] }}
        run: |
          cp wrangler.toml wrangler.toml.bak

          for i in {1..30}; do
            WORKER_NAME="quadpro$i"
            WORKER_DOMAIN="quadpro$i.${{ matrix.config.name }}"

            echo "🚀 Deploying $WORKER_NAME → $WORKER_DOMAIN"

            cp wrangler.toml.bak wrangler.temp.toml

            sed -i "s|\${WORKER_NAME}|$WORKER_NAME|g" wrangler.temp.toml
            sed -i "s|\${WORKER_DOMAIN}|$WORKER_DOMAIN|g" wrangler.temp.toml
            sed -i "s|\${ACCOUNT_ID}|${{ matrix.config.account_id }}|g" wrangler.temp.toml
            sed -i "s|\${KV_NAMESPACE_ID}|${{ matrix.config.kv_namespace_id }}|g" wrangler.temp.toml

            wrangler deploy --config wrangler.temp.toml

            echo "✅ Selesai deploy $WORKER_NAME → $WORKER_DOMAIN"
          done

          rm -f wrangler.temp.toml
